name: C++ CI

on:
  push:
    branches:
      - main
      - feature/github_actions

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download source code
        uses: actions/checkout@v6

      - name: Configure CMake
        run: >
          cmake
          -S .
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Package
        run: cmake --build build --target package

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "v0.0.${{ github.run_number }}" \
            build/*.deb \
            --target "${{ github.sha }}" \
            --title "Release 0.0.${{ github.run_number }}" \
            --notes "Automatic build ${{ github.run_number }}"